name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Build and test with Maven
        run: mvn -B -DskipTests=false test